abc: ssk

spring:
  ##redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    #    host: 172.31.64.11
    password: YanTest201905!-
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
    # 连接超时时间（毫秒）
    timeout: 10000
    sentinel:
      #哨兵监听redis server名称
      master: mymaster
      #哨兵的配置列表
      nodes: 172.31.64.11:27001,172.31.64.11:27002,172.31.64.11:27003
#      nodes: 172.31.64.11:27001